apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: auwalu5/java_app:1
        name: vote
        ports:
        - containerPort: 8080
          name: vote
      imagePullSecrets:
      - name: acr-secret # Reference to the ACR secret
