steps:
  # Step 1: Set up environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" != "prod" ]; then
          echo "Not on prod branch. Exiting."
          exit 0
        fi

  # Step 2: Checkout the code
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'git'
    args: ['clone', 'https://github.com/thedevops-mohi/java-app.git']

  # Step 3: Change to the cloned directory
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - 'cd java-app'

    # Step 4: Install Apache Maven 3.9.7
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-L'
      - 'https://downloads.apache.org/maven/maven-3/3.9.7/binaries/apache-maven-3.9.7-bin.tar.gz'
      - '-o'
      - 'apache-maven-3.9.7-bin.tar.gz'
  - name: 'gcr.io/cloud-builders/tar'
    args:
      - 'xvzf'
      - 'apache-maven-3.9.7-bin.tar.gz'
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'mv apache-maven-3.9.7 /usr/local/apache-maven'

  # Step 5: Set up environment to use Apache Maven 3.9.7
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export MAVEN_HOME=/usr/local/apache-maven
        export PATH=$MAVEN_HOME/bin:$PATH
        mvn --version

  # Step 6: Build the Java application
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export MAVEN_HOME=/usr/local/apache-maven
        export PATH=$MAVEN_HOME/bin:$PATH
        cd $REPO_NAME
        mvn install
        mvn package

  # Step 5: Build the Docker image using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']

  # Step 6: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'

substitutions:
  _REPO_NAME: java-application'
  _PROJECT_ID: 'curious-domain-372904'

# Only trigger this build on the 'prod' branch
# Adjust this section according to how you set up your triggers
# trigger:
#   branch: 'prod'
