steps:
  # Step 1: Set up environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" != "prod" ]; then
          echo "Not on prod branch. Exiting."
          exit 0
        fi

  # Step 2: Checkout the code
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'git'
    args: ['clone', 'https://github.com/thedevops-mohi/java-app', '.']

  # Step 3: Set up JDK
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['mvn', 'install']
  
  # Step 4: Build the Java application
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['mvn', 'package']

  # Step 5: Build the Docker image using Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']

  # Step 6: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'

# substitutions:
#   _REPO_NAME: thedevops-mohi/java-app'
#   _PROJECT_ID: 'curious-domain-372904'

# Only trigger this build on the 'prod' branch
# Adjust this section according to how you set up your triggers
# trigger:
#   branch: 'prod'
