apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"prom-pvc","namespace":"mon"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"16Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-08-30T05:45:02Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: prom-pvc
  namespace: mon
  resourceVersion: "41043942"
  uid: 23d44e57-d4b5-4e9f-a1d3-8dedcc96ddc6
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  volumeMode: Filesystem
  volumeName: prom-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 16Gi
  phase: Bound
