apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"alert-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"8Gi"},"nfs":{"path":"/mnt/nfs_share","server":"192.168.0.150"}}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-08-30T06:06:09Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: jenkins-pv
  resourceVersion: "41046535"
  uid: 8dbdbe13-70a8-42f8-935b-0014ea5e06b7
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: storage-prom-alertmanager-0
    namespace: mon
    resourceVersion: "41046479"
    uid: 3f56d976-84c6-4675-a7d8-7962a96d2102
  nfs:
    path: /mnt/nfs_share
    server: 192.168.0.150
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
